server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    treads:
      max: 50
      min-spare: 5


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/milberonja/config-repo
          default-label: main #The gitHub branch
          timeout: 5 #Time limit to establish a connection with the remote repository
          clone-on-start: true #Clone the remote repository locally on startup
          force-pull: true # Forces pulling the remote repository and discarding any local changes
